# Brewfile to be used with `brew bundle`

# Taps
tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"

# Formulae
brew "git"
brew "htop"
brew "rust"
brew "valgrind"
brew "tmux"
brew "vim"
brew "python"
brew "python3"
brew "leiningen"

# Casks
cask "java"
cask "iterm2"
