#!/usr/bin/env bash

icon="$HOME/.config/i3/lock.png"
tmpbg="/tmp/screen.png"
bgpic="$HOME/Pictures/lock_bg.jpg"

x="$(xrandr | grep -oP 'primary \K[0-9]+')"
y="$(xrandr | grep -oP 'primary [0-9]+x\K[0-9]+')"
x_2=$(((x / 2) - 100))
y_2=$(((y / 2) - 100))

gm convert "$bgpic" -scale 10% -scale 1000% -resize ${x}x${y}! "$tmpbg"
gm convert "$tmpbg" -draw "image Over ${x_2},${y_2} 200,200 ${icon}" "$tmpbg"
i3lock -u -i "$tmpbg"

